[package]
name = "codio-content-id"
version.workspace = true
edition.workspace = true

[dependencies]
sha2.workspace = true
bs58.workspace = true
serde.workspace = true
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"
