[package]
name = "codio-content"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
bs58 = "0.5"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.5"
hex = "0.4"

[dev-dependencies]
